---

- hosts: all
  become: true
  tasks: 

  - name: install apache2 package
    yum:
      name: httpd
      state: absent

  - name: update index
    yum:
      update_cache: yes
      state: latest
